package:
  name: crane
  version: 0.15.0
  epoch: 0
  description: Tool for interacting with remote images and registries.
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - busybox
      - go

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/google/go-containerregistry/archive/v${{package.version}}/v${{package.version}}.tar.gz
      expected-sha256: ceb5f2eed1a010f23e5e49319fc836fa8966418e1d151140e336c36383e57405

  - runs: |
      CGO_ENABLED=0 go build \
        -trimpath -ldflags \
        "-buildid= -X github.com/google/go-containerregistry/cmd/crane/cmd.Version=${{package.version}} -X github.com/google/go-containerregistry/pkg/v1/remote/transport.Version=${{package.version}}" \
        -o "${{targets.destdir}}/usr/bin/crane" ./cmd/crane

  - uses: strip

update:
  enabled: true
  github:
    identifier: google/go-containerregistry
    strip-prefix: v
