package:
  name: dgraph
  version: 23.0.0
  epoch: 0
  description: The GitOps Toolkit Helm reconciler, for declarative Helming
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
      - curl

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/dgraph-io/dgraph
      tag: v${{package.version}}
      expected-commit: 38980bc4a44352094c15ddfe4b606a8f05b48e81

  - runs: |
      make install_oss
      mkdir -p ${{targets.destdir}}/usr/bin
      mv $(go env GOPATH)/bin/dgraph ${{targets.destdir}}/usr/bin

  - uses: strip

update:
  enabled: true
  github:
    identifier: dgraph-io/dgraph
    strip-prefix: v
    tag-filter: v
