package:
  name: gradle-8
  version: 8.2.0-M1 # When bumping this, also bump the provides below!
  epoch: 0
  description: A Java project management and project comprehension tool.
  copyright:
    - license: Apache-2.0
  dependencies:
    provides:
      - gradle=8.1.1
environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - bash
      - tini
      - git
      - patch
      - zip
      # note: the comment below is not the case while we evaluate the right way to build gradle we have swapped from
      # using the boostrap gradle to gradlewrapper.
      #
      # The first time this is built, it depends on gradle-stage0.yaml being built first,
      # using pre-built gradle binaries, which `provides` a gradle package at an earlier version.
      # Afterwards it depends on previous versions of this package built from source.
      - openjdk-11
pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/gradle/gradle
      tag: v${{package.version}}
      expected-commit: 0f7d6b14b563ca06bfd34d2dde25d0f1f93279e3
  - runs: |
      # Do not use the gradle wrapper, ensure we're using the bootstrap version.
      ./gradlew :distributions-full:binDistributionZip

      unzip subprojects/distributions-full/build/distributions/gradle-${{package.version}}-bin.zip
      cd gradle-${{package.version}}-*
      mkdir -p ${{targets.destdir}}/usr/share/java/gradle
      mkdir -p ${{targets.destdir}}/usr/share/java/gradle/bin
      mkdir -p ${{targets.destdir}}/usr/share/java/gradle/lib

      mv lib/* ${{targets.destdir}}/usr/share/java/gradle/lib
      mv bin/* ${{targets.destdir}}/usr/share/java/gradle/bin

      mkdir -p ${{targets.destdir}}/usr/bin
      ln -sf /usr/share/java/gradle/bin/gradle ${{targets.destdir}}/usr/bin/gradle
update:
  enabled: true
  ignore-regex-patterns:
    - -M*
  github:
    identifier: gradle/gradle
    strip-prefix: v
    use-tag: true
    tag-filter: "v8."
