package:
  name: grype
  version: 0.56.0
  epoch: 0
  description: Vulnerability scanner for container images, filesystems, and SBOMs
  target-architecture:
    - all
  copyright:
    - license: Apache-2.0
      paths:
        - "*"
environment:
  contents:
    packages:
      - ca-certificates-bundle
      - busybox
      - go
pipeline:
  - uses: fetch
    with:
      uri: https://github.com/anchore/grype/archive/v${{package.version}}/grype-${{package.version}}.tar.gz
      expected-sha512: 6fb050e6b2083d2cc2bc8e8035fd74e681397063e17e3ba26eaf188cceb0c3a6fb2a97d83e8868125d53ff3f23ed0a9042daaf2f48e77815dc7b47d564543470
  - runs: |
      CGO_ENABLED=0 go build \
        -ldflags "-X github.com/anchore/grype/internal/version.version=${{package.version}}" \
        -o "${{targets.destdir}}/usr/bin/grype"
