package:
  name: grype
  version: 0.58.0
  epoch: 0
  description: Vulnerability scanner for container images, filesystems, and SBOMs
  target-architecture:
    - all
  copyright:
    - license: Apache-2.0
      paths:
        - "*"
environment:
  contents:
    packages:
      - ca-certificates-bundle
      - busybox
      - go
pipeline:
  - uses: fetch
    with:
      uri: https://github.com/anchore/grype/archive/v${{package.version}}/grype-${{package.version}}.tar.gz
      expected-sha512: b2277d9acf1fe2978bdabc6411eb670fef50759f26e66af3a815a1f6086a371171b5ad03d03e37ba78c66495bbd8e164c60135edfbdcab989859cc71164f9024
  - runs: |
      CGO_ENABLED=0 go build \
        -ldflags "-X github.com/anchore/grype/internal/version.version=${{package.version}}" \
        -o "${{targets.destdir}}/usr/bin/grype"
