package:
  name: kyverno-cli
  version: 1.9.3
  epoch: 0
  description: Kubernetes Native Policy Management CLI
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - busybox
      - go

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/kyverno/kyverno/archive/v${{package.version}}/v${{package.version}}.tar.gz
      expected-sha256: dbc29ccb9a54479addc0f1c6c60879a50b9c20e0bd917cd6e0d123636f68e770

  - uses: go/build
    with:
      packages: ./cmd/cli/kubectl-kyverno
      ldflags: -X github.com/kyverno/kyverno/pkg/version.BuildVersion=${{package.version}}
      output: kyverno-cli

  - uses: strip

update:
  enabled: true
  github:
    identifier: kyverno/kyverno
    strip-prefix: v
