package:
  name: kyverno-cli
  version: 1.10.0
  epoch: 0
  description: Kubernetes Native Policy Management CLI
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - busybox
      - go

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/kyverno/kyverno/archive/v${{package.version}}/v${{package.version}}.tar.gz
      expected-sha256: 10a762a28468c48393fb0e28a95c2865312a9b0c9e70cdb86974e9bbea3be72e

  - uses: go/build
    with:
      packages: ./cmd/cli/kubectl-kyverno
      ldflags: -s -w -X github.com/kyverno/kyverno/pkg/version.BuildVersion=${{package.version}}
      output: kyverno-cli

  - uses: strip

update:
  enabled: true
  github:
    identifier: kyverno/kyverno
    strip-prefix: v
