package:
  name: llvm-libunwind
  version: 16.0.4
  epoch: 0
  description: LLVM version of libunwind library
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - llvm15
      - llvm15-dev
      - cmake
      - samurai

pipeline:
  - uses: fetch
    with:
      expected-sha256: 5412af4d6bcdbca6444b7c001fa5b83e9910cac496b4005ee1f8744a46502ffc
      uri: https://github.com/llvm/llvm-project/releases/download/llvmorg-${{package.version}}/libunwind-${{package.version}}.src.tar.xz

  - uses: fetch
    with:
      uri: https://github.com/llvm/llvm-project/releases/download/llvmorg-${{package.version}}/cmake-${{package.version}}.src.tar.xz
      expected-sha256: 1a366c5f7a7a0efa2f7ede960717f26f5332df28adc9b3c47516a859de2ccf7b
      strip-components: 0

  - runs: |
      mv cmake-${{package.version}}.src cmake-src

  - runs: |
      cmake -B build -G Ninja -Wno-dev \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCLANG_BUILT_STANDALONE=TRUE \
        -DLLVM_CONFIG=/usr/lib/llvm15/bin/llvm-config \
        -DCMAKE_MODULE_PATH=/home/build/cmake-src/Modules \
        -DLIBUNWIND_INSTALL_HEADERS=YES

  - runs: |
      cmake --build build

  - runs: |
      DESTDIR="${{targets.destdir}}" cmake --install build

subpackages:
  - name: llvm-libunwind-static
    pipeline:
      - uses: split/static
    description: LLVM version of libunwind library (static library)

  - name: llvm-libunwind-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - llvm-libunwind
    description: LLVM version of libunwind library (development files)

update:
  enabled: true
  release-monitor:
    identifier: 1830
