package:
  name: neo4j
  version: "5.6.0"
  epoch: 0
  description:
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      attestation:
      license: GPL-3.0
  dependencies:
    runtime:
      - openjdk-17-jre
      - bash

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - curl
      - maven
      - openjdk-17
      - bash
      - wolfi-base
      - wolfi-baselayout

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/neo4j/neo4j
      tag: ${{package.version}}
      expected-commit: 5ad4387ed521f169a737f9836402dbac8759a9fc

  - runs: |
      export LANG=en_US.UTF-8
      export JAVA_HOME=/usr/lib/jvm/openjdk

      mvn install -DskipTests=true -T4.0C -q
      mvn package -DskipTests=true -T4.0C -q
      mkdir -p ${{targets.destdir}}/usr/share/java/neo4j

      tar --strip-components=1 -xf packaging/standalone/target/neo4j-*.tar.gz -C ${{targets.destdir}}/usr/share/java/neo4j

      mkdir -p ${{targets.destdir}}/usr/bin
      for i in neo4j neo4j-admin cypershell; do
        ln -sf /usr/share/java/neo4j/bin/$i ${{targets.destdir}}/usr/bin/$i
      done

subpackages:
  - name: neo4j-oci-entrypoint
    description: OCI entrypoint for Neo4j
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/bin
          mv entrypoint.sh ${{targets.subpkgdir}}/usr/bin/entrypoint.sh

update:
  enabled: true
  github:
    identifier: neo4j/neo4j
    use-tag: true
