package:
  name: nerdctl
  version: 1.2.1
  epoch: 0
  description: Docker-compatible CLI for containerd, with support for Compose, Rootless, eStargz, OCIcrypt, IPFS, ...
  copyright:
    - license: Apache-2.0
environment:
  contents:
    packages:
      - go
      - busybox
      - ca-certificates-bundle
      - build-base
pipeline:
  - uses: fetch
    with:
      expected-sha256: ee913c25a8b9cf15d31d1f7bf9405b586a68b02c7e70538194700dec08730b3a
      uri: https://github.com/containerd/nerdctl/archive/v${{package.version}}.tar.gz
  - runs: |
      make nerdctl
      install -Dm755 ./_output/nerdctl ${{targets.destdir}}/usr/bin/nerdctl
update:
  enabled: true
  github:
    identifier: containerd/nerdctl
    strip-prefix: v
