package:
  name: poetry
  version: 1.5.0
  epoch: 0
  description: "Python packaging and dependency management made easy"
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - python3
      - py3-gpep517
      - py3-setuptools

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/python-poetry/poetry/archive/${{package.version}}.tar.gz
      expected-sha256: 51dc32599edba7eafeb5038282aa9c5629d1e1ac72061075b0a302b3546bd839

  - runs: |
      POETRY_HOME=/usr/share/pypoetry python3 install-poetry.py -y --path .
      mkdir -p ${{targets.destdir}}/usr/share
      mkdir -p ${{targets.destdir}}/usr/bin
      mv /usr/share/pypoetry ${{targets.destdir}}/usr/share
      ln -sf /usr/share/pypoetry/venv/bin/poetry ${{targets.destdir}}/usr/bin/

  - uses: strip

update:
  enabled: true
  github:
    identifier: python-poetry/poetry
