package:
  name: py3-pygments
  version: 2.15.0
  epoch: 0
  description: Syntax highlighting package written in Python
  copyright:
    - license: BSD-2-Clause

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - py3-setuptools
      - python3
      - py3-gpep517
      - py3-wheel

pipeline:
  - uses: fetch
    with:
      expected-sha256: f7e36cffc4c517fbc252861b9a6e4644ca0e5abadf9a113c72d1358ad09b9500
      uri: https://files.pythonhosted.org/packages/source/P/Pygments/Pygments-${{package.version}}.tar.gz

  - runs: |
      backend="$(python3 -m gpep517 get-backend)"

      python3 -m gpep517 build-wheel --wheel-dir dist --backend "$backend" --output-fd 1

  - runs: |
      python3 -m installer -d "${{targets.destdir}}" dist/Pygments-*.whl

      mkdir -p ${{targets.destdir}}/usr/bin
      ln -s pygmentize ${{targets.destdir}}/usr/bin/pygmentize-3

subpackages:
  - name: py3-pygments-doc
    pipeline:
      - runs: |
          destdir=${{targets.subpkgdir}}/usr/share/doc/py3-pygments

          cd "$builddir"

          install -m 644 -D doc/pygmentize.1 \
            ${{targets.subpkgdir}}/usr/share/man/man1/pygmentize.1

          mkdir -p "$destdir"
          cp AUTHORS CHANGES LICENSE "$destdir"/

          # Note: The documentation in the doc directory needs to be generated
          # by py-sphinx
          cp -R ./doc/docs/* "$destdir"/
      - uses: split/manpages
    description: py3-pygments manpages

update:
  enabled: true
  release-monitor:
    identifier: 3986
