package:
  name: py3-pip
  version: "23.0"
  epoch: 0
  description: "tool for installing and managing python packages"
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      attestation: TODO
      license: MIT
  dependencies:
    runtime:
      - python3
      - py3-contextlib2
      - py3-pep517
      - py3-retrying
      - py3-setuptools
environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - build-base
      - python3
      - py3-contextlib2
      - py3-pep517
      - py3-retrying
      - py3-setuptools
pipeline:
  - uses: fetch
    with:
      uri: https://files.pythonhosted.org/packages/source/p/pip/pip-${{package.version}}.tar.gz
      expected-sha256: aee438284e82c8def684b0bcc50b1f6ed5e941af97fa940e83e2e8ef1a59da9b
  - runs: |
      python3 setup.py build
  - runs: |
      python3 setup.py install --prefix=/usr --root="${{targets.destdir}}"
  - uses: strip
