package:
  name: py3-urllib3
  version: 1.26.15
  epoch: 1
  description: "HTTP library with thread-safe connection pooling, file post, and more"
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - build-base
      - py3-pip

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/urllib3/urllib3.git
      tag: ${{package.version}}
      expected-commit: 95ca35211d23d8baf7646e1f60aa31e3650178a8

  - runs: pip install . --prefix=/usr --root=${{targets.destdir}}

  - uses: strip

update:
  enabled: true
  github:
    identifier: urllib3/urllib3
