package:
  name: py3-urllib3
  version: 2.0.0a4
  epoch: 0
  description: "HTTP library with thread-safe connection pooling, file post, and more"
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - build-base
      - python3
      - py3-setuptools

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/urllib3/urllib3/releases/download/${{package.version}}/urllib3-${{package.version}}.tar.gz
      expected-sha256: acf734cd9087d1753c3f3911ed2f012b8f42d6105fec85917ae5a46a1ea5ff27

  - runs: |
      python3 setup.py build

  - runs: |
      python3 setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

update:
  enabled: true
  github:
    identifier: urllib3/urllib3
