package:
  name: rekor-cli
  version: 1.1.0
  epoch: 0
  description: Rekor command line interface tool
  target-architecture:
    - all
  copyright:
    - license: Apache-2.0
      paths:
        - "*"

environment:
  contents:
    packages:
      - git

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/sigstore/rekor
      tag: v${{package.version}}
      expected-commit: 4a6592612dc015f24d0700b6d274b3663d128ad8

  - uses: go/build
    with:
      packages: ./cmd/rekor-cli/main.go
      ldflags: -X sigs.k8s.io/release-utils/version.gitVersion=${{package.version}} -X sigs.k8s.io/release-utils/version.gitCommit=$(git rev-parse --short HEAD)
      output: rekor-cli

update:
  enabled: true
  github:
    identifier: sigstore/rekor
    strip-prefix: v
