package:
  name: tkn
  version: 0.30.0
  epoch: 1
  description: A CLI for interacting with Tekton!
  copyright:
    - license: Apache-2.0
environment:
  contents:
    packages:
      - ca-certificates-bundle
      - busybox
      - go
      - build-base
pipeline:
  - uses: fetch
    with:
      uri: https://github.com/tektoncd/cli/archive/v${{package.version}}.tar.gz
      expected-sha256: 377e54a0d861a43216ecb63eddd2815ef3fb8f3e514eac6ad22cd9f148132642
  - runs: |
      make bin/tkn
      install -Dm755 ./bin/tkn ${{targets.destdir}}/usr/bin/tkn
update:
  enabled: true
  github:
    identifier: tektoncd/cli
    strip-prefix: v
