package:
  name: vim
  version: 9.0.1573
  epoch: 0
  description: "Improved vi-style text editor"
  copyright:
    - license: Vim

environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - build-base
      - ncurses-dev
      - lua5.3-dev
      - python3-dev

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/vim/vim/archive/v${{package.version}}.tar.gz
      expected-sha256: 32f95e065282d66985c2c6442bf8821258727236650da7984643554ad9130dc1

  - runs: |
      # vim seems to manually set FORTIFY_SOURCE=1, and setting both breaks the build
      export CFLAGS=${CFLAGS/-Wp,-D_FORTIFY_SOURCE=3/}
      export CPPFLAGS="$CFLAGS"
      export CXXFLAGS="$CFLAGS"
      ./configure \
        --build=$CBUILD \
        --host=$CHOST \
        --prefix=/usr \
        --enable-luainterp \
        --enable-python3interp=dynamic \
        --without-x \
        --disable-nls \
        --enable-multibyte \
        --enable-gui=no \
        --with-lua-prefix=/usr/lua5.3 \
        --with-compiledby="Wolfi Linux"

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

update:
  enabled: true
  github:
    identifier: vim/vim
    strip-prefix: v
    use-tag: true
